[theme]
primaryColor = "#1F3864"
backgroundColor = "#f4f6f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#1F1F1F"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
